package com.formuladock.core.model.formula.model

object BuiltinFormulas {
    const val ROAD_TRIP_COST_ID: String = "example_road_trip_cost"
    const val HOME_PAINT_ESTIMATOR_ID: String = "example_home_paint_estimator"
    const val FREELANCE_PROJECT_QUOTE_ID: String = "example_freelance_project_quote"
    const val MONTHLY_HOUSEHOLD_BUDGET_ID: String = "example_monthly_household_budget"
    const val HOME_ELECTRICITY_BILL_ID: String = "example_home_electricity_bill"

    fun allSeedFormulas(now: Long): List<FormulaDefinition> {
        return listOf(
            roadTripCost(now),
            homePaintEstimator(now),
            freelanceProjectQuote(now),
            monthlyHouseholdBudget(now),
            homeElectricityBill(now),
        )
    }

    fun roadTripCost(now: Long): FormulaDefinition {
        return FormulaDefinition(
            id = ROAD_TRIP_COST_ID,
            title = "Road Trip Cost Planner",
            description = "Estimate fuel usage, total travel cost, cost per traveler, and carbon emissions for a road trip.",
            inputs = listOf(
                FormulaInput(
                    id = "road_trip_input_distance",
                    key = "distance_km",
                    label = "Travel Distance",
                    defaultValue = "500",
                    unit = "km",
                    required = true,
                    sortOrder = 0,
                ),
                FormulaInput(
                    id = "road_trip_input_fuel_efficiency",
                    key = "fuel_efficiency",
                    label = "Fuel Consumption",
                    defaultValue = "7.5",
                    unit = "L/100 km",
                    required = true,
                    sortOrder = 1,
                ),
                FormulaInput(
                    id = "road_trip_input_fuel_price",
                    key = "fuel_price",
                    label = "Fuel Price",
                    defaultValue = "1.65",
                    unit = "per L",
                    required = true,
                    sortOrder = 2,
                ),
                FormulaInput(
                    id = "road_trip_input_tolls",
                    key = "tolls",
                    label = "Tolls",
                    defaultValue = "25",
                    unit = "CNY",
                    required = false,
                    sortOrder = 3,
                ),
                FormulaInput(
                    id = "road_trip_input_parking",
                    key = "parking",
                    label = "Parking Fees",
                    defaultValue = "15",
                    unit = "CNY",
                    required = false,
                    sortOrder = 4,
                ),
                FormulaInput(
                    id = "road_trip_input_travelers",
                    key = "travelers",
                    label = "Number of Travelers",
                    defaultValue = "2",
                    unit = "people",
                    required = true,
                    sortOrder = 5,
                ),
            ),
            constants = listOf(
                FormulaConstant(
                    id = "road_trip_constant_contingency",
                    key = "contingency_percent",
                    label = "Contingency Budget",
                    value = "8",
                    unit = "%",
                    sortOrder = 0,
                ),
                FormulaConstant(
                    id = "road_trip_constant_co2",
                    key = "co2_per_liter",
                    label = "CO2 Emission per Liter",
                    value = "2.31",
                    unit = "kg/L",
                    sortOrder = 1,
                ),
            ),
            outputs = listOf(
                FormulaOutput(
                    id = "road_trip_output_fuel_needed",
                    key = "fuel_needed",
                    label = "Estimated Fuel Needed",
                    expression = "distance_km * fuel_efficiency / 100",
                    unit = "L",
                    precision = 2,
                    sortOrder = 0,
                ),
                FormulaOutput(
                    id = "road_trip_output_fuel_cost",
                    key = "fuel_cost",
                    label = "Estimated Fuel Cost",
                    expression = "fuel_needed * fuel_price",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 1,
                ),
                FormulaOutput(
                    id = "road_trip_output_base_cost",
                    key = "base_trip_cost",
                    label = "Base Trip Cost",
                    expression = "sum(fuel_cost, tolls, parking)",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 2,
                ),
                FormulaOutput(
                    id = "road_trip_output_planned_cost",
                    key = "planned_trip_cost",
                    label = "Planned Trip Cost",
                    expression = "pctAdd(base_trip_cost, contingency_percent)",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 3,
                ),
                FormulaOutput(
                    id = "road_trip_output_cost_per_person",
                    key = "cost_per_person",
                    label = "Cost per Traveler",
                    expression = "planned_trip_cost / max(travelers, 1)",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 4,
                ),
                FormulaOutput(
                    id = "road_trip_output_co2",
                    key = "estimated_co2",
                    label = "Estimated CO2 Emissions",
                    expression = "fuel_needed * co2_per_liter",
                    unit = "kg",
                    precision = 2,
                    sortOrder = 5,
                ),
            ),
            isBuiltin = false,
            sortOrder = 4,
            createdAt = now,
            updatedAt = now,
        )
    }

    fun homePaintEstimator(now: Long): FormulaDefinition {
        return FormulaDefinition(
            id = HOME_PAINT_ESTIMATOR_ID,
            title = "Home Paint Estimator",
            description = "Estimate paintable wall area, required paint, number of paint cans, and unused paint.",
            inputs = listOf(
                FormulaInput(
                    id = "paint_input_room_length",
                    key = "room_length",
                    label = "Room Length",
                    defaultValue = "5",
                    unit = "m",
                    required = true,
                    sortOrder = 0,
                ),
                FormulaInput(
                    id = "paint_input_room_width",
                    key = "room_width",
                    label = "Room Width",
                    defaultValue = "4",
                    unit = "m",
                    required = true,
                    sortOrder = 1,
                ),
                FormulaInput(
                    id = "paint_input_room_height",
                    key = "room_height",
                    label = "Room Height",
                    defaultValue = "2.8",
                    unit = "m",
                    required = true,
                    sortOrder = 2,
                ),
                FormulaInput(
                    id = "paint_input_door_count",
                    key = "door_count",
                    label = "Number of Doors",
                    defaultValue = "1",
                    unit = null,
                    required = false,
                    sortOrder = 3,
                ),
                FormulaInput(
                    id = "paint_input_window_count",
                    key = "window_count",
                    label = "Number of Windows",
                    defaultValue = "2",
                    unit = null,
                    required = false,
                    sortOrder = 4,
                ),
                FormulaInput(
                    id = "paint_input_coats",
                    key = "coats",
                    label = "Number of Coats",
                    defaultValue = "2",
                    unit = null,
                    required = true,
                    sortOrder = 5,
                ),
                FormulaInput(
                    id = "paint_input_can_size",
                    key = "can_size",
                    label = "Paint Can Size",
                    defaultValue = "5",
                    unit = "L",
                    required = true,
                    sortOrder = 6,
                ),
            ),
            constants = listOf(
                FormulaConstant(
                    id = "paint_constant_door_area",
                    key = "door_area",
                    label = "Average Door Area",
                    value = "1.9",
                    unit = "m²",
                    sortOrder = 0,
                ),
                FormulaConstant(
                    id = "paint_constant_window_area",
                    key = "window_area",
                    label = "Average Window Area",
                    value = "1.5",
                    unit = "m²",
                    sortOrder = 1,
                ),
                FormulaConstant(
                    id = "paint_constant_coverage",
                    key = "coverage_per_liter",
                    label = "Paint Coverage",
                    value = "10",
                    unit = "m²/L",
                    sortOrder = 2,
                ),
                FormulaConstant(
                    id = "paint_constant_waste",
                    key = "waste_percent",
                    label = "Paint Waste Allowance",
                    value = "10",
                    unit = "%",
                    sortOrder = 3,
                ),
            ),
            outputs = listOf(
                FormulaOutput(
                    id = "paint_output_gross_wall_area",
                    key = "gross_wall_area",
                    label = "Gross Wall Area",
                    expression = "2 * (room_length + room_width) * room_height",
                    unit = "m²",
                    precision = 2,
                    sortOrder = 0,
                ),
                FormulaOutput(
                    id = "paint_output_opening_area",
                    key = "opening_area",
                    label = "Door and Window Area",
                    expression = "door_count * door_area + window_count * window_area",
                    unit = "m²",
                    precision = 2,
                    sortOrder = 1,
                ),
                FormulaOutput(
                    id = "paint_output_paintable_area",
                    key = "paintable_area",
                    label = "Paintable Wall Area",
                    expression = "max(gross_wall_area - opening_area, 0)",
                    unit = "m²",
                    precision = 2,
                    sortOrder = 2,
                ),
                FormulaOutput(
                    id = "paint_output_coated_area",
                    key = "coated_area",
                    label = "Total Coated Area",
                    expression = "paintable_area * max(coats, 0)",
                    unit = "m²",
                    precision = 2,
                    sortOrder = 3,
                ),
                FormulaOutput(
                    id = "paint_output_required_liters",
                    key = "required_liters",
                    label = "Paint Required",
                    expression = "pctAdd(coated_area / coverage_per_liter, waste_percent)",
                    unit = "L",
                    precision = 2,
                    sortOrder = 4,
                ),
                FormulaOutput(
                    id = "paint_output_cans_required",
                    key = "cans_required",
                    label = "Paint Cans Required",
                    expression = "ceil(required_liters / max(can_size, 0.1))",
                    unit = "cans",
                    precision = 0,
                    sortOrder = 5,
                ),
                FormulaOutput(
                    id = "paint_output_unused_paint",
                    key = "unused_paint",
                    label = "Estimated Unused Paint",
                    expression = "max(cans_required * can_size - required_liters, 0)",
                    unit = "L",
                    precision = 2,
                    sortOrder = 6,
                ),
            ),
            isBuiltin = false,
            sortOrder = 5,
            createdAt = now,
            updatedAt = now,
        )
    }

    fun freelanceProjectQuote(now: Long): FormulaDefinition {
        return FormulaDefinition(
            id = FREELANCE_PROJECT_QUOTE_ID,
            title = "Freelance Project Quote",
            description = "Calculate a client quote, platform fees, estimated taxes, take-home income, and effective hourly rate.",
            inputs = listOf(
                FormulaInput(
                    id = "freelance_input_hours",
                    key = "estimated_hours",
                    label = "Estimated Work Hours",
                    defaultValue = "40",
                    unit = "hours",
                    required = true,
                    sortOrder = 0,
                ),
                FormulaInput(
                    id = "freelance_input_hourly_rate",
                    key = "hourly_rate",
                    label = "Hourly Rate",
                    defaultValue = "50",
                    unit = "CNY/hour",
                    required = true,
                    sortOrder = 1,
                ),
                FormulaInput(
                    id = "freelance_input_expenses",
                    key = "project_expenses",
                    label = "Project Expenses",
                    defaultValue = "200",
                    unit = "CNY",
                    required = false,
                    sortOrder = 2,
                ),
                FormulaInput(
                    id = "freelance_input_platform_fee",
                    key = "platform_fee_percent",
                    label = "Platform Fee",
                    defaultValue = "10",
                    unit = "%",
                    required = true,
                    sortOrder = 3,
                ),
                FormulaInput(
                    id = "freelance_input_tax",
                    key = "income_tax_percent",
                    label = "Estimated Income Tax",
                    defaultValue = "20",
                    unit = "%",
                    required = true,
                    sortOrder = 4,
                ),
                FormulaInput(
                    id = "freelance_input_contingency",
                    key = "contingency_percent",
                    label = "Project Contingency",
                    defaultValue = "15",
                    unit = "%",
                    required = true,
                    sortOrder = 5,
                ),
            ),
            constants = emptyList(),
            outputs = listOf(
                FormulaOutput(
                    id = "freelance_output_labor_cost",
                    key = "labor_cost",
                    label = "Labor Cost",
                    expression = "estimated_hours * hourly_rate",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 0,
                ),
                FormulaOutput(
                    id = "freelance_output_base_cost",
                    key = "base_project_cost",
                    label = "Base Project Cost",
                    expression = "labor_cost + project_expenses",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 1,
                ),
                FormulaOutput(
                    id = "freelance_output_client_quote",
                    key = "client_quote",
                    label = "Recommended Client Quote",
                    expression = "pctAdd(base_project_cost, contingency_percent)",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 2,
                ),
                FormulaOutput(
                    id = "freelance_output_platform_fee",
                    key = "platform_fee",
                    label = "Platform Fee",
                    expression = "pctOf(platform_fee_percent, client_quote)",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 3,
                ),
                FormulaOutput(
                    id = "freelance_output_taxable_income",
                    key = "taxable_income",
                    label = "Estimated Taxable Income",
                    expression = "max(client_quote - platform_fee - project_expenses, 0)",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 4,
                ),
                FormulaOutput(
                    id = "freelance_output_income_tax",
                    key = "estimated_income_tax",
                    label = "Estimated Income Tax",
                    expression = "pctOf(income_tax_percent, taxable_income)",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 5,
                ),
                FormulaOutput(
                    id = "freelance_output_take_home",
                    key = "take_home_income",
                    label = "Estimated Take-Home Income",
                    expression = "client_quote - platform_fee - project_expenses - estimated_income_tax",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 6,
                ),
                FormulaOutput(
                    id = "freelance_output_effective_rate",
                    key = "effective_hourly_rate",
                    label = "Effective Hourly Rate",
                    expression = "take_home_income / max(estimated_hours, 1)",
                    unit = "CNY/hour",
                    precision = 2,
                    sortOrder = 7,
                ),
                FormulaOutput(
                    id = "freelance_output_margin",
                    key = "take_home_margin",
                    label = "Take-Home Margin",
                    expression = "take_home_income / max(client_quote, 0.01) * 100",
                    unit = "%",
                    precision = 2,
                    sortOrder = 8,
                ),
            ),
            isBuiltin = false,
            sortOrder = 6,
            createdAt = now,
            updatedAt = now,
        )
    }

    fun monthlyHouseholdBudget(now: Long): FormulaDefinition {
        return FormulaDefinition(
            id = MONTHLY_HOUSEHOLD_BUDGET_ID,
            title = "Monthly Household Budget",
            description = "Analyze monthly expenses, achievable savings, savings shortfall, and remaining disposable income.",
            inputs = listOf(
                FormulaInput(
                    id = "budget_input_income",
                    key = "net_income",
                    label = "Monthly Net Income",
                    defaultValue = "8000",
                    unit = "CNY",
                    required = true,
                    sortOrder = 0,
                ),
                FormulaInput(
                    id = "budget_input_housing",
                    key = "housing",
                    label = "Housing",
                    defaultValue = "2500",
                    unit = "CNY",
                    required = true,
                    sortOrder = 1,
                ),
                FormulaInput(
                    id = "budget_input_utilities",
                    key = "utilities",
                    label = "Utilities",
                    defaultValue = "400",
                    unit = "CNY",
                    required = true,
                    sortOrder = 2,
                ),
                FormulaInput(
                    id = "budget_input_groceries",
                    key = "groceries",
                    label = "Groceries",
                    defaultValue = "1200",
                    unit = "CNY",
                    required = true,
                    sortOrder = 3,
                ),
                FormulaInput(
                    id = "budget_input_transport",
                    key = "transport",
                    label = "Transportation",
                    defaultValue = "500",
                    unit = "CNY",
                    required = true,
                    sortOrder = 4,
                ),
                FormulaInput(
                    id = "budget_input_insurance",
                    key = "insurance",
                    label = "Insurance",
                    defaultValue = "300",
                    unit = "CNY",
                    required = false,
                    sortOrder = 5,
                ),
                FormulaInput(
                    id = "budget_input_debt",
                    key = "debt_payments",
                    label = "Debt Payments",
                    defaultValue = "600",
                    unit = "CNY",
                    required = false,
                    sortOrder = 6,
                ),
                FormulaInput(
                    id = "budget_input_discretionary",
                    key = "discretionary_spending",
                    label = "Discretionary Spending",
                    defaultValue = "900",
                    unit = "CNY",
                    required = false,
                    sortOrder = 7,
                ),
                FormulaInput(
                    id = "budget_input_savings_percent",
                    key = "savings_target_percent",
                    label = "Savings Target",
                    defaultValue = "20",
                    unit = "%",
                    required = true,
                    sortOrder = 8,
                ),
            ),
            constants = emptyList(),
            outputs = listOf(
                FormulaOutput(
                    id = "budget_output_essential_expenses",
                    key = "essential_expenses",
                    label = "Essential Expenses",
                    expression = "sum(housing, utilities, groceries, transport, insurance, debt_payments)",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 0,
                ),
                FormulaOutput(
                    id = "budget_output_total_expenses",
                    key = "total_expenses",
                    label = "Total Expenses",
                    expression = "essential_expenses + discretionary_spending",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 1,
                ),
                FormulaOutput(
                    id = "budget_output_remaining_before_savings",
                    key = "remaining_before_savings",
                    label = "Remaining Before Savings",
                    expression = "net_income - total_expenses",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 2,
                ),
                FormulaOutput(
                    id = "budget_output_target_savings",
                    key = "target_savings",
                    label = "Target Savings",
                    expression = "pctOf(savings_target_percent, net_income)",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 3,
                ),
                FormulaOutput(
                    id = "budget_output_actual_savings",
                    key = "actual_savings",
                    label = "Achievable Savings",
                    expression = "max(min(remaining_before_savings, target_savings), 0)",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 4,
                ),
                FormulaOutput(
                    id = "budget_output_savings_gap",
                    key = "savings_gap",
                    label = "Savings Target Shortfall",
                    expression = "max(target_savings - actual_savings, 0)",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 5,
                ),
                FormulaOutput(
                    id = "budget_output_expense_ratio",
                    key = "expense_ratio",
                    label = "Expense-to-Income Ratio",
                    expression = "total_expenses / max(net_income, 0.01) * 100",
                    unit = "%",
                    precision = 2,
                    sortOrder = 6,
                ),
                FormulaOutput(
                    id = "budget_output_disposable_income",
                    key = "disposable_income",
                    label = "Disposable Income After Savings",
                    expression = "remaining_before_savings - actual_savings",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 7,
                ),
            ),
            isBuiltin = false,
            sortOrder = 7,
            createdAt = now,
            updatedAt = now,
        )
    }

    fun homeElectricityBill(now: Long): FormulaDefinition {
        return FormulaDefinition(
            id = HOME_ELECTRICITY_BILL_ID,
            title = "Home Electricity Bill",
            description = "Estimate a monthly electricity bill using peak and off-peak rates, credits, tax, and household size.",
            inputs = listOf(
                FormulaInput(
                    id = "electricity_input_peak_usage",
                    key = "peak_usage",
                    label = "Peak Electricity Usage",
                    defaultValue = "180",
                    unit = "kWh",
                    required = true,
                    sortOrder = 0,
                ),
                FormulaInput(
                    id = "electricity_input_off_peak_usage",
                    key = "off_peak_usage",
                    label = "Off-Peak Electricity Usage",
                    defaultValue = "120",
                    unit = "kWh",
                    required = true,
                    sortOrder = 1,
                ),
                FormulaInput(
                    id = "electricity_input_peak_rate",
                    key = "peak_rate",
                    label = "Peak Electricity Rate",
                    defaultValue = "0.85",
                    unit = "CNY/kWh",
                    required = true,
                    sortOrder = 2,
                ),
                FormulaInput(
                    id = "electricity_input_off_peak_rate",
                    key = "off_peak_rate",
                    label = "Off-Peak Electricity Rate",
                    defaultValue = "0.45",
                    unit = "CNY/kWh",
                    required = true,
                    sortOrder = 3,
                ),
                FormulaInput(
                    id = "electricity_input_fixed_charge",
                    key = "fixed_charge",
                    label = "Monthly Service Charge",
                    defaultValue = "25",
                    unit = "CNY",
                    required = true,
                    sortOrder = 4,
                ),
                FormulaInput(
                    id = "electricity_input_credit",
                    key = "energy_credit",
                    label = "Renewable Energy Credit",
                    defaultValue = "20",
                    unit = "CNY",
                    required = false,
                    sortOrder = 5,
                ),
                FormulaInput(
                    id = "electricity_input_tax",
                    key = "tax_percent",
                    label = "Electricity Tax",
                    defaultValue = "6",
                    unit = "%",
                    required = true,
                    sortOrder = 6,
                ),
                FormulaInput(
                    id = "electricity_input_members",
                    key = "household_members",
                    label = "Household Members",
                    defaultValue = "3",
                    unit = "people",
                    required = true,
                    sortOrder = 7,
                ),
            ),
            constants = listOf(
                FormulaConstant(
                    id = "electricity_constant_months",
                    key = "months_per_year",
                    label = "Months per Year",
                    value = "12",
                    unit = null,
                    sortOrder = 0,
                ),
                FormulaConstant(
                    id = "electricity_constant_emission_factor",
                    key = "emission_factor",
                    label = "Grid Carbon Emission Factor",
                    value = "0.42",
                    unit = "kg CO2/kWh",
                    sortOrder = 1,
                ),
            ),
            outputs = listOf(
                FormulaOutput(
                    id = "electricity_output_total_usage",
                    key = "total_usage",
                    label = "Total Electricity Usage",
                    expression = "sum(peak_usage, off_peak_usage)",
                    unit = "kWh",
                    precision = 2,
                    sortOrder = 0,
                ),
                FormulaOutput(
                    id = "electricity_output_peak_cost",
                    key = "peak_cost",
                    label = "Peak Energy Cost",
                    expression = "peak_usage * peak_rate",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 1,
                ),
                FormulaOutput(
                    id = "electricity_output_off_peak_cost",
                    key = "off_peak_cost",
                    label = "Off-Peak Energy Cost",
                    expression = "off_peak_usage * off_peak_rate",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 2,
                ),
                FormulaOutput(
                    id = "electricity_output_subtotal",
                    key = "bill_subtotal",
                    label = "Bill Subtotal",
                    expression = "max(peak_cost + off_peak_cost + fixed_charge - energy_credit, 0)",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 3,
                ),
                FormulaOutput(
                    id = "electricity_output_tax",
                    key = "electricity_tax",
                    label = "Electricity Tax",
                    expression = "pctOf(tax_percent, bill_subtotal)",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 4,
                ),
                FormulaOutput(
                    id = "electricity_output_monthly_bill",
                    key = "monthly_bill",
                    label = "Estimated Monthly Bill",
                    expression = "bill_subtotal + electricity_tax",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 5,
                ),
                FormulaOutput(
                    id = "electricity_output_annual_bill",
                    key = "annual_bill",
                    label = "Estimated Annual Bill",
                    expression = "monthly_bill * months_per_year",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 6,
                ),
                FormulaOutput(
                    id = "electricity_cost_per_person",
                    key = "electricity_cost_per_person",
                    label = "Monthly Cost per Person",
                    expression = "monthly_bill / max(household_members, 1)",
                    unit = "CNY",
                    precision = 2,
                    sortOrder = 7,
                ),
                FormulaOutput(
                    id = "electricity_output_emissions",
                    key = "estimated_emissions",
                    label = "Estimated Monthly CO2 Emissions",
                    expression = "total_usage * emission_factor",
                    unit = "kg",
                    precision = 2,
                    sortOrder = 8,
                ),
            ),
            isBuiltin = false,
            sortOrder = 8,
            createdAt = now,
            updatedAt = now,
        )
    }
}
